### ISSUE TITLE
Date Time Processing

### ISSUE THREAD

**Issue by mhowe0422** [CodeForPittsburgh/fishfryform#10]
We know the date for Ash Wednesday and Friday's in Lent. We just need to list the dates, check if the locations is open on that date and add the time range. An additional box for locations that have two open times per date.

**Comment by gassc** [comment]
For 2018, the above suggested change will be addressed in a UI re-design and in the pre-population of this year's data with last year's data, using the venue's previous times but updating the dates (for a start).

Potentially, behind the scenes, we'll also make a change in how this stuff is stored. I'm currently mulling a NoSQL database, with the `events` being an object indexed by [ISO 8061-spec interval strings](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals). We can parse those with Moment-JS and [Moment-Range](https://github.com/rotaready/moment-range).

**Comment by gassc** [comment]
After looking at a bunch of event/booking/scheduling sites, I've implemented a new datetime picker that should make this easier. I've also prepopulated the data with this year's dates at last year's times, so hopefully less work there.
