### ISSUE TITLE
Update dependencies per security warnings from github

### ISSUE THREAD

**Issue by catskul** [CodeForPittsburgh/fishfryform#26]
Known high severity security vulnerability detected in uglify-js < 2.6.0 defined in package-lock.json.
package-lock.json update suggested: uglify-js ~> 2.6.0.

Known moderate severity security vulnerability detected in hoek < 5.0.3 defined in package-lock.json.
package-lock.json update suggested: hoek ~> 5.0.3.

Known moderate severity security vulnerability detected in pycrypto <=2.6.1defined in Pipfile.lock.

Known high severity security vulnerability detected in mime < 1.4.1 defined in package-lock.json.
package-lock.json update suggested: mime ~> 1.4.1.

Known high severity security vulnerability detected in mixin-deep <1.3.1 defined in package-lock.json.
package-lock.json update suggested: mixin-deep ~> 1.3.1.

**Comment by gassc** [comment]
@catskul - on my todo list.
